@extends('layouts.app')
@section('title','Servicios de la actividad | Respuesta ASONACOP')
@section('content')
<section class="page-heading project-indicator-heading"><div><p class="eyebrow">{{ $actividadIndicador->indicadorProyecto->proyecto->codigo }} · {{ $actividadIndicador->indicadorProyecto->indicador->codigo }}</p><h1>Servicios de la actividad</h1><p class="muted"><strong>{{ $actividadIndicador->actividad->codigo }}</strong> · {{ $actividadIndicador->actividad->descripcion }}</p></div><div class="heading-actions"><a class="button button-secondary" href="{{ route('indicador-proyecto.actividades.index',$actividadIndicador->indicadorProyecto) }}">← Volver a actividades</a><button class="button button-primary" type="button" data-bs-toggle="modal" data-bs-target="#modalAgregarServicio" @disabled($serviciosDisponibles->isEmpty())>+ Agregar servicio</button></div></section>
<section class="content-card">@if($asignaciones->isEmpty())<div class="empty-state"><p>Esta actividad todavía no tiene servicios asignados.</p></div>@else
<div class="table-wrap"><table><thead><tr><th>Servicio</th><th>Descripción</th><th>Cantidad disponible</th><th>Estado</th><th></th></tr></thead><tbody>
@foreach($asignaciones as $asignacion)<tr><td><strong>{{ $asignacion->servicio->nombre }}</strong></td><td class="catalog-description">{{ $asignacion->servicio->descripcion ?: 'Sin descripción' }}</td><td><form class="assignment-inline-form" action="{{ route('servicio-actividad.update',$asignacion) }}" method="post">@csrf @method('PUT')<input type="number" name="cantidad_disponible" value="{{ $asignacion->cantidad_disponible }}" min="0" placeholder="Sin cantidad"><select name="estatus"><option value="1" @selected($asignacion->estatus)>Activo</option><option value="0" @selected(!$asignacion->estatus)>Inactivo</option></select><button class="button button-secondary button-small" type="submit">Guardar</button></form></td><td><span class="status {{ $asignacion->estatus ? 'status-active' : 'status-inactive' }}">{{ $asignacion->estatus ? 'Activo' : 'Inactivo' }}</span></td><td class="row-actions"><form action="{{ route('servicio-actividad.destroy',$asignacion) }}" method="post" onsubmit="return confirm('¿Quitar este servicio de la actividad?');">@csrf @method('DELETE')<button class="danger-link" type="submit">Quitar</button></form></td></tr>@endforeach
</tbody></table></div><div class="pagination">{{ $asignaciones->links() }}</div>@endif</section>
<div class="modal fade" id="modalAgregarServicio" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content catalog-modal"><form action="{{ route('actividad-indicador.servicios.store',$actividadIndicador) }}" method="post">@csrf<div class="modal-header"><h2 class="modal-title">Agregar servicio</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><label>Servicio *<select name="servicio_id" required><option value="">Seleccione un servicio</option>@foreach($serviciosDisponibles as $servicio)<option value="{{ $servicio->id }}" @selected(old('servicio_id')==$servicio->id)>{{ $servicio->nombre }}{{ $servicio->descripcion ? ' — '.$servicio->descripcion : '' }}</option>@endforeach</select></label><label>Cantidad disponible<input type="number" name="cantidad_disponible" value="{{ old('cantidad_disponible') }}" min="0" placeholder="0"></label></div><div class="modal-footer"><button class="button button-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="button button-primary" type="submit">Guardar</button></div></form></div></div></div>
@endsection
@push('scripts')@if($errors->any())<script>bootstrap.Modal.getOrCreateInstance(document.getElementById('modalAgregarServicio')).show();</script>@endif @endpush
