@extends('layouts.app')
@section('title','Proyectos | Respuesta ASONACOP')
@section('content')
<section class="page-heading"><div><p class="eyebrow">Configuraci&oacute;n</p><h1>Proyectos</h1><p class="muted">Administre los proyectos y sus periodos de ejecuci&oacute;n.</p></div><a class="button button-primary" href="{{ route('proyectos.create') }}">+ Nuevo proyecto</a></section>
<section class="content-card">@if($proyectos->isEmpty())<div class="empty-state"><p>No hay proyectos registrados.</p></div>@else
<div class="table-wrap"><table><thead><tr><th>C&oacute;digo</th><th>Descripci&oacute;n</th><th>Donante</th><th>Ubicaci&oacute;n</th><th>Periodo</th><th>Estado</th><th>Sectores</th><th></th></tr></thead><tbody>
@foreach($proyectos as $proyecto)<tr><td><strong>{{ $proyecto->codigo }}</strong></td><td>{{ $proyecto->descripcion }}</td><td>{{ $proyecto->donante->nombre }}</td><td><strong>{{ $proyecto->estados->pluck('name')->join(', ') ?: 'Sin estados' }}</strong><br><small>{{ $proyecto->municipios->isEmpty() ? 'Todos los municipios de los estados' : $proyecto->municipios->pluck('name')->join(', ') }}</small></td><td>{{ $proyecto->inicio?->format('d/m/Y') ?? 'Sin fecha' }}<br><small>al {{ $proyecto->fin?->format('d/m/Y') ?? 'Sin fecha' }}</small></td><td><span class="status {{ $proyecto->estatus?'status-active':'status-inactive' }}">{{ $proyecto->estatus?'Activo':'Inactivo' }}</span></td><td><a class="indicator-count-link" href="{{ route('proyectos.sectores.index',$proyecto) }}">Gestionar ({{ $proyecto->sectores_count }})</a></td><td class="row-actions"><a href="{{ route('proyectos.show',$proyecto) }}">Ver</a><a href="{{ route('proyectos.edit',$proyecto) }}">Editar</a><form action="{{ route('proyectos.destroy',$proyecto) }}" method="post" onsubmit="return confirm('&iquest;Eliminar este proyecto y sus asignaciones?');">@csrf @method('DELETE')<button class="danger-link" type="submit">Eliminar</button></form></td></tr>@endforeach
</tbody></table></div><div class="pagination">{{ $proyectos->links() }}</div>@endif</section>
@endsection
